### ISSUE TITLE
Support for relaxations

### ISSUE THREAD

**Issue by algebravic** [cvxpy/cvxpy#1574]
I would like to ask that the following features be added for relaxations:

1) Lagrangian relaxations.  It would be nice to have a model, plus a specific set of constraints to be dualized.  The output would be a parametrized model (by the Lagrange multipliers) where the specified constraints are moved to the objective.

2) SDP relaxations.  A similar request -- if a model has quadratic constraints, to be able to automatically produce the SDP relaxation.

3) Relaxation of some (or all) of integrality constraints.

If I wanted to do some of these myself, where is the stuff documented to be able to take apart the expression trees?

**Comment by SteveDiamond** [comment]
Sorry for the delayed response.


1. You can get the arguments of constraints programmatically
(see https://www.cvxpy.org/api_reference/cvxpy.constraints.html) and form the Lagrangian along the lines you described.

2. The most relevant code is this package: https://github.com/cvxgrp/qcqp
It does SDP relaxations of non-convex QCQPs automatically. However it only works with CVXPY 0.4 unfortunately.

3. Integrality constraints can only be introduced by creating integer variables, so you can do ``problem.variables()`` and check if ``variable.attributes['integer']`` is True.

**Comment by algebravic** [comment]
Steven, Thanks for the response.

Victor

**Comment by alirezaqazavi** [comment]
@[SteveDiamond](https://github.com/SteveDiamond)
Hello
I force google colab to use cvxpy 0.4.5
but by running example code in[https://github.com/cvxgrp/qcqp]( https://github.com/cvxgrp/qcqp) and I get this error:
`
AttributeError: 'LinOp' object has no attribute 'shape'`

please guide me to remove this error and work with qcqp
many thanks

**Comment by Transurgeon** [comment]
closing this issue since it seems it has been resolved.
