### ISSUE TITLE
AttributeError when creating a boolean Parameter with value=False

### ISSUE THREAD

**Issue by avibagheri** [cvxpy/cvxpy#3284]
I'm getting an error when creating a boolean Parameter with value=False:

```
import cvxpy as cp
bool_param = cp.Parameter(boolean=True, name="bool_param", value=False)
```

Full Traceback:

```
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "/venv_py312/lib/python3.12/site-packages/cvxpy/expressions/constants/parameter.py", line 62, in __init__
    super(Parameter, self).__init__(shape, value, **kwargs)
  File "/venv_py312/lib/python3.12/site-packages/cvxpy/expressions/leaf.py", line 171, in __init__
    self.value = value
  File "/venv_py312/lib/python3.12/site-packages/cvxpy/expressions/leaf.py", line 491, in value
    self.save_value(self._validate_value(val))
  File "/venv_py312/lib/python3.12/site-packages/cvxpy/expressions/leaf.py", line 556, in _validate_value
    projection = self.project(val, sparse_path)
  File "/venv_py312/lib/python3.12/site-packages/cvxpy/expressions/leaf.py", line 415, in project
    new_val = np.atleast_1d(val.astype(np.float64, copy=True))
AttributeError: 'int' object has no attribute 'astype'
```

I'm using cvxpy 1.8.2 with Python 3.12. The Expected behavior is that the parameter should accept True/False without errors. It was working with older version of cvxpy (1.6.6).

**Comment by dhru189** [comment]
hi @avibagheri i want to work on it .
