### ISSUE TITLE
Import error with latest version of scipy installed

### ISSUE THREAD

**Issue by ehtec** [cvxpy/cvxpy#2158]
**Describe the bug**
When using this together with the latest version 1.11.0 of scipy (from pypi), you get an error when importing cvxpy:

```
File "/usr/local/lib/python3.10/site-packages/cvxpy/__init__.py", line 18, in <module>
    import cvxpy.interface.scipy_wrapper
  File "/usr/local/lib/python3.10/site-packages/cvxpy/interface/scipy_wrapper.py", line 37, in <module>
    method = getattr(spmatrix, method_name)
AttributeError: type object 'spmatrix' has no attribute '__div__'
```

**Version**
 - OS: Debian 11
 - CVXPY Version: 1.3.1

**Additional context**
I encountered this because my CI pipeline is failing since the latest version of scipy was released a few hours ago. It works with scipy 1.10.1 (the second-latest version).

**Comment by phschiele** [comment]
@ehtec Thanks for reporting this! I was able to replicate the issue and found the following:

- As stated in the message, the error originates from [scipy_wrapper.py](https://github.com/cvxpy/cvxpy/blob/master/cvxpy/interface/scipy_wrapper.py)
- Adding a `try ... except` around the loop in the file fixes all tests
- Indeed, so does commenting out all of the contents in the file
- I used the below snippet to understand the intended behavior under SciPy 1.10:

```py
import cvxpy as cp
import numpy as np
import scipy.sparse as sp

a = cp.Variable((1,3))
b = sp.coo_matrix(np.arange(3))
a + b
>>> Expression(AFFINE, UNKNOWN, (1, 3))
b + a
>>> Expression(AFFINE, UNKNOWN, (1, 3))
a.__add__(b)
>>> Expression(AFFINE, UNKNOWN, (1, 3))
b.__add__(a)
>>> NotImplemented
```

My thoughts are:
1. At the very least, we had some missing test coverage on the intended effect of these operations
2. If anything, we should probably `raise NotImplementedError` instead of `return NotImplemented`
3. The operation `b + a` does not fail because it is wrapped again by https://github.com/cvxpy/cvxpy/blob/8f3e2b95051d2fc0977735ebfebdd34b53295a13/cvxpy/expressions/expression.py#L46-L51, so the combination of the wrappers is likely not intended behavior

The files have been there for quite a long time, so maybe @cvxpy/maintainers can give some context.

**Comment by niklasvm** [comment]
I can confirm we are experiencing the same issue since a few hours ago

**Comment by Gazzzzyy** [comment]
Hi all, we're also experiencing the same issues on our end! Will keep an eye on this thread :)

**Comment by detrin** [comment]
I can confirm we are facing the same issue here

**Comment by phschiele** [comment]
Thanks, everyone for the heads-ups! It looks like everyone who is installing `cvxpy` with updated SciPy is getting these errors. Anyone else finding this issue, just give a :+1: to the first post and subscribe to the issue :)

**Comment by detrin** [comment]
There are changes in API

[this release](https://github.com/scipy/scipy/blob/d8c8a8b07fa77fe86b0e58814c7140ca926dd1a4/scipy/sparse/_matrix.py#L4)
[last release](https://github.com/scipy/scipy/blob/c1ed5ece8ffbf05356a22a8106affcd11bd3aee0/scipy/sparse/_base.py#L688)

I have a sense that it is not going to be one line fix.

**Comment by phschiele** [comment]
Linking @h-vetinari's PR in the SciPy repo: https://github.com/scipy/scipy/issues/18749

**Comment by SteveDiamond** [comment]
The proposal here seems fine to me:
https://github.com/scipy/scipy/issues/18749#issuecomment-1607426961

The purpose of scipy_wrapper.py is to enable operator overloading with SciPy sparse matrices. It's not needed for NumPy ndarrays because NumPy has better native support for operator overloading.

**Comment by SteveDiamond** [comment]
I started a PR to fix this:
https://github.com/cvxpy/cvxpy/pull/2159
@phschiele feel free to add try/catch and/or more tests to the PR.

**Comment by phschiele** [comment]
Closed via #2159, patch is in the works.

**Comment by niklasvm** [comment]
> Closed via #2159, patch is in the works.

When will this fix be released to pypi?

**Comment by phschiele** [comment]
The patch is now available on PyPI: https://pypi.org/project/cvxpy/1.3.2/
Patches for 1.2 and 1.1 will follow shortly.

**Comment by detrin** [comment]
Much appreciated, thanks
